name: Reusable Tutorials Workflow

on:
  workflow_call:
    inputs:
      smoke_test:
        required: false
        type: boolean
        default: true
      use_stable_pytorch_gpytorch:
        required: false
        type: boolean
        default: false
      use_stable_ax:
        required: false
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      smoke_test:
        description: Use smoke test
        required: false
        type: boolean
        default: true
      use_stable_pytorch_gpytorch:
        description: Use min required pytorch & gpytorch
        required: false
        type: boolean
        default: false
      use_stable_ax:
        description: Use stable Ax
        required: false
        type: boolean
        default: false

jobs:
  tutorials:
    name: Run tutorials
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Fetch all history for all tags and branches
      # We need to do this so setuptools_scm knows how to set the BoTorch version.
      run: git fetch --prune --unshallow
    - if: ${{ !inputs.use_stable_pytorch_botorch }}
      name: Install latest PyTorch & GPyTorch
      run: |
        pip install git+https://github.com/cornellius-gp/gpytorch.git
    - if: ${{ inputs.use_stable_pytorch_botorch }}
      name: Install min required PyTorch & GPyTorch
      run: |
        python setup.py egg_info
        req_txt="botorch.egg-info/requires.txt"
        min_torch_version=$(grep '\btorch>=' ${req_txt} | sed 's/[^0-9.]//g')
        min_gpytorch_version=$(grep '\bgpytorch>=' ${req_txt} | sed 's/[^0-9.]//g')
        pip install "torch==${min_torch_version}" "gpytorch==${min_gpytorch_version}"
    - if: ${{ !inputs.use_stable_ax }}
      name: Install latest Ax
      env:
        # This is so Ax's setup doesn't install a pinned BoTorch version.
        ALLOW_BOTORCH_LATEST: true
      run: |
        pip install git+https://github.com/facebook/Ax.git
    - if: ${{ always() }}
      name: Install BoTorch with tutorials dependencies
      env:
        ALLOW_BOTORCH_LATEST: true
      run: |
        pip install .[tutorials]
    - if: ${{ inputs.smoke_test }}
      name: Run tutorials with smoke test
      run: |
        python scripts/run_tutorials.py -p "$(pwd)" -s
    - if: ${{ !inputs.smoke_test }}
      name: Run tutorials without smoke test
      run: |
        python scripts/run_tutorials.py -p "$(pwd)"
