name: Tutorials

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  call-workflow:
    name: Run tutorials with smoke test on latest PyTorch / GPyTorch / Ax
    uses: ./.github/workflows/reusable_tutorials.yml@main
    with:
      smoke_test: true
      use_stable_pytorch_gpytorch: false
      use_stable_ax: false
